FROM prow/bazel2-env:latest as builder
LABEL maintainer="Xie Weizhi" description="The prow hookagent module image"
WORKDIR test-infra
COPY . .
RUN bazel build prow/external-plugins/hookagent

FROM centos:latest
ARG RPKG=openEuler-Advisor-1.0-3.oe1.noarch.rpm
RUN yum -y install ${RPKG} \
    &&pip3 -y install pyyaml
WORKDIR /root/
COPY --from=builder /usr/local/test-infra/bazel-bin/prow/external-plugins/hookagent/linux_amd64_pure_stripped/hookagent .
ENTRYPOINT ["./hookagent"]
EXPOSE 8080